#!/usr/bin/env tsx
/**
 * Regenerate @omada/sdk types from the canonical OpenAPI spec.
 *
 * Reads:  specs/omada_api.json  (override with --spec <path>)
 * Writes:
 *   packages/sdk/src/generated/schema.d.ts    — openapi-typescript output
 *   packages/sdk/src/generated/operations.ts  — operationId → {method,path,tags,summary}
 *   packages/sdk/src/generated/index.ts       — barrel re-export
 *
 * Usage:
 *   pnpm generate
 *   pnpm generate --spec specs/snapshots/2026-04-23.json
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const HTTP_METHODS = ["get", "post", "put", "patch", "delete"] as const;
type HttpMethod = (typeof HTTP_METHODS)[number];

interface OpenAPIOperation {
  operationId?: string;
  tags?: string[];
  summary?: string;
  deprecated?: boolean;
}

type OpenAPIPathItem = {
  [K in HttpMethod]?: OpenAPIOperation;
};

interface OpenAPISpec {
  openapi: string;
  info: { title: string; version: string };
  paths?: Record<string, OpenAPIPathItem>;
  tags?: Array<{ name: string; description?: string }>;
}

interface OperationInfo {
  operationId: string;
  method: HttpMethod;
  path: string;
  tags: string[];
  summary?: string;
  deprecated: boolean;
}

function parseArgs(argv: string[]): { specPath: string } {
  const args = argv.slice(2);
  const specIdx = args.indexOf("--spec");
  const fallback = "specs/omada_api.json";
  if (specIdx < 0) return { specPath: fallback };
  const value = args[specIdx + 1];
  if (!value) {
    console.error("[generate] --spec requires a path");
    process.exit(2);
  }
  return { specPath: value };
}

function buildOperationsIndex(spec: OpenAPISpec): {
  index: Record<string, OperationInfo>;
  stats: { paths: number; ops: number; collisions: number; perTag: Record<string, number> };
} {
  const index: Record<string, OperationInfo> = {};
  const perTag: Record<string, number> = {};
  let collisions = 0;
  let ops = 0;

  const paths = spec.paths ?? {};
  for (const [path, item] of Object.entries(paths)) {
    for (const method of HTTP_METHODS) {
      const op = item[method];
      if (!op?.operationId) continue;
      ops += 1;
      if (index[op.operationId]) {
        collisions += 1;
        console.warn(
          `[generate] duplicate operationId "${op.operationId}" at ${method.toUpperCase()} ${path}`,
        );
      }
      const entry: OperationInfo = {
        operationId: op.operationId,
        method,
        path,
        tags: op.tags ?? [],
        deprecated: op.deprecated ?? false,
        ...(op.summary !== undefined ? { summary: op.summary } : {}),
      };
      index[op.operationId] = entry;
      for (const tag of entry.tags) perTag[tag] = (perTag[tag] ?? 0) + 1;
    }
  }

  return {
    index,
    stats: { paths: Object.keys(paths).length, ops, collisions, perTag },
  };
}

function renderOperationsTs(index: Record<string, OperationInfo>): string {
  const entries = Object.values(index)
    .sort((a, b) => a.operationId.localeCompare(b.operationId))
    .map((info) => {
      const summary =
        info.summary !== undefined ? `    summary: ${JSON.stringify(info.summary)},\n` : "";
      return (
        `  ${JSON.stringify(info.operationId)}: {\n` +
        `    operationId: ${JSON.stringify(info.operationId)},\n` +
        `    method: ${JSON.stringify(info.method)},\n` +
        `    path: ${JSON.stringify(info.path)},\n` +
        `    tags: ${JSON.stringify(info.tags)},\n` +
        summary +
        `    deprecated: ${String(info.deprecated)},\n` +
        `  },`
      );
    })
    .join("\n");

  return `/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/generate.ts. DO NOT EDIT BY HAND.
 * Regenerate with \`pnpm generate\`.
 */

export type HttpMethod = "get" | "post" | "put" | "patch" | "delete";

export interface OperationInfo {
  readonly operationId: string;
  readonly method: HttpMethod;
  readonly path: string;
  readonly tags: readonly string[];
  readonly summary?: string;
  readonly deprecated: boolean;
}

export const operations = {
${entries}
} as const satisfies Record<string, OperationInfo>;

export type OperationId = keyof typeof operations;
`;
}

function renderBarrelTs(): string {
  return `/* eslint-disable */
// AUTO-GENERATED by scripts/generate.ts. Do not edit.
// Re-export point for the generated SDK surface.

export * from "./operations.js";
// Typed path schema (from openapi-typescript). Only types, no runtime.
export type { components, paths, operations as schemaOperations } from "./schema.js";
`;
}

async function main(): Promise<void> {
  const scriptDir = dirname(fileURLToPath(import.meta.url));
  const repoRoot = resolve(scriptDir, "..");
  const { specPath } = parseArgs(process.argv);
  const specAbs = resolve(repoRoot, specPath);

  console.log(`[generate] reading spec: ${specAbs}`);
  const rawSpec = readFileSync(specAbs, "utf8");
  const spec = JSON.parse(rawSpec) as OpenAPISpec;
  console.log(`[generate] ${spec.info.title} ${spec.info.version} (openapi ${spec.openapi})`);

  const outDir = resolve(repoRoot, "packages/sdk/src/generated");
  mkdirSync(outDir, { recursive: true });

  // 1. openapi-typescript → schema.d.ts
  console.log(`[generate] running openapi-typescript ...`);
  const t0 = Date.now();
  const ast = await openapiTS(pathToFileURL(specAbs));
  const body = astToString(ast);
  const schemaHeader = `/* eslint-disable */
// AUTO-GENERATED from ${specPath} by scripts/generate.ts. Do not edit.
// Regenerate with \`pnpm generate\`.

`;
  writeFileSync(resolve(outDir, "schema.d.ts"), schemaHeader + body, "utf8");
  const schemaMs = Date.now() - t0;
  console.log(
    `[generate]   → schema.d.ts (${(body.length / 1024).toFixed(1)} KiB, ${schemaMs} ms)`,
  );

  // 2. operations map
  const { index, stats } = buildOperationsIndex(spec);
  writeFileSync(resolve(outDir, "operations.ts"), renderOperationsTs(index), "utf8");
  console.log(
    `[generate]   → operations.ts (${stats.ops} ops across ${stats.paths} paths, ${stats.collisions} collisions)`,
  );

  // 3. barrel
  writeFileSync(resolve(outDir, "index.ts"), renderBarrelTs(), "utf8");
  console.log(`[generate]   → index.ts`);

  // 4. tag summary
  const topTags = Object.entries(stats.perTag)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 10)
    .map(([name, count]) => `${name}(${count})`)
    .join(", ");
  console.log(`[generate] top tags: ${topTags}`);
  console.log(`[generate] ✓ done`);
}

main().catch((err) => {
  console.error("[generate] FAILED:", err);
  process.exit(1);
});
